# Generated by Django 5.2 on 2025-04-20 20:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoemLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('position', models.PositiveIntegerField()),
                ('grade', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('syllable_count', models.PositiveIntegerField(editable=False)),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='poems.poem')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('poem', 'position')},
            },
        ),
    ]
