# Generated by Django 5.2 on 2025-04-21 15:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('position', models.PositiveIntegerField()),
                ('grade', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('syllable_count', models.PositiveIntegerField(editable=False)),
                ('is_syllable_override', models.BooleanField(default=False)),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='versus.verse')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('verse', 'position')},
            },
        ),
    ]
