# Generated by Django 5.2 on 2025-04-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
