# Generated by Django 5.2 on 2025-04-22 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('versus', '0002_ensure_slugs'),
        ('versus', '0002_verse_slug'),
    ]

    operations = [
    ]
