# Generated by Django 5.2 on 2025-04-20 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0002_poemline'),
    ]

    operations = [
        migrations.AddField(
            model_name='poemline',
            name='is_syllable_override',
            field=models.BooleanField(default=False),
        ),
    ]
