# Generated by Django 5.2 on 2025-04-22 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('versus', '0003_merge_0002_ensure_slugs_0002_verse_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verse',
            name='content',
        ),
    ]
