# Generated by Django 5.2 on 2025-04-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versus', '0004_remove_verse_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='pattern',
            field=models.TextField(blank=True, help_text="Enter the poem's pattern or structure"),
        ),
    ]
